### ISSUE TITLE
Usage of pynetsim

### ISSUE THREAD

**Issue by Phirotest** [arbor-jjones/pynetsim#3]
How does pynetsim and its logging function works ? Are there any demos ?

**Comment by OblackatO** [comment]
Hello @Phirotest,

If I understood well, Pynetsim uses the default lib of python called logging. 

At the beginning of each file of each available protocol a logger is init, using (__ name __) : A default var init by python by default which points to the namespace of the file.

Finally, you can see in [1] that the configurations specified for the level of the logger in [2] are taken in consideration. 

But why are you asking anyway ? 

 [1] : https://github.com/jjo-sec/pynetsim/blob/master/daemon.py
 [2] : https://github.com/jjo-sec/pynetsim/blob/master/pynetsim.conf

**Comment by Phirotest** [comment]
Thanks !! At first, I thought that all the logs will be logged to a file but after seeing the config files, I realised that it was actually being output to the terminal. One last question is how does the ftp and http works in pynetsim as I am not able to capture those traffic even though my client default dns is set to pynetsim IP address and I did HTTP request with the client?

**Comment by OblackatO** [comment]
I am not sure that I can help you here without having more information. 

You should follow the simple setup rules explained in the description of Pynetsim. 
What you need to do is: Redirect the traffic that arrives from a Y interface in the host running pynetsim to a X port of your choice. 

To do so you should reconfigure the IPTABLES of your host. 

I hope that helps, do not hesitate to post a screenshot of your problem, or to close this Issue if you have no more questions.
